---
abstract: 'A database schema for Module::CoreList'
author:
  - 'Chris Williams'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-CoreList-DBSchema
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Module::CoreList::DBSchema:
    file: lib/Module/CoreList/DBSchema.pm
    version: 0.02
requires:
  Clone: 0.31
  Module::CoreList: 2.29
  SQL::Abstract: 1.65
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/module-corelist-dbschema/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/module-corelist-dbschema.git
version: 0.02
